# Site wide configuration

title: Apartment Homesteading
description: "Homesteading in my apartment, planning for my tiny house"
logo: abandonedhomestead-160x160.jpg #120x120
teaser: default.png # 400x250 px default teaser image used in image archive grid
locale:
#url: http://0.0.0.0:4000
url: http://apartmenthomesteading.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: The Apartment Homesteader
  email: 
  twitter:
  google:
    ad-client: ca-pub-6605857117185825
    ad-slot: 7037990191
  bio: "I'm documenting my progress on my way to an off-grid tiny house"
  avatar: abandonedhomestead-160x160.jpg # 160x160 px image for author byline
disqus-shortname: apartmenthomesteading


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
